{
  created_at: 'Mon Oct 14 17:41:00 +0000 2019',
  id: 1183799882672291800,
  id_str: '1183799882672291840',
  text: '#bbtheHeartBot cheer me up bb',
  source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 32109719,
    id_str: '32109719',
    name: 'allison busse',
    screen_name: 'idkallison',
    location: 'Portland, OR',
    url: 'http://allisonbusse.com',
    description: null,
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 68,
    friends_count: 95,
    listed_count: 3,
    favourites_count: 279,
    statuses_count: 726,
    created_at: 'Thu Apr 16 19:08:28 +0000 2009',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme12/bg.gif',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme12/bg.gif',
    profile_background_tile: false,
    profile_link_color: '19CF86',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/141690636/Photo_98_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/141690636/Photo_98_normal.jpg',
    default_profile: false,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: { hashtags: [ [Object] ], urls: [], user_mentions: [], symbols: [] },
  favorited: false,
  retweeted: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1571074860624'
}
{
  created_at: 'Mon Oct 14 17:41:05 +0000 2019',
  id: 1183799904507793400,
  id_str: '1183799904507793409',
  text: "@idkallison I can respond with a bot based on a hashtag, so sorry to anyone who fallows me I'm testing for a projec… https://t.co/GG9COhgGo8",
  truncated: true,
  entities: {
    hashtags: [],
    symbols: [],
    user_mentions: [ [Object] ],
    urls: [ [Object] ]
  },
  source: '<a href="https://radiant-dawn-69636.herokuapp.com" rel="nofollow">BBtheHeartBot</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: 32109719,
  in_reply_to_user_id_str: '32109719',
  in_reply_to_screen_name: 'idkallison',
  user: {
    id: 1366070046,
    id_str: '1366070046',
    name: 'Maeve Griffin',
    screen_name: 'maeve_griffin',
    location: 'Philadelphia',
    description: '',
    url: 'http://t.co/mEUU8QLkHo',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 12,
    friends_count: 95,
    listed_count: 0,
    created_at: 'Sat Apr 20 03:48:15 +0000 2013',
    favourites_count: 37,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 31,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/3560794574/129e529d9fcb81c88016e31afcdfce02_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/3560794574/129e529d9fcb81c88016e31afcdfce02_normal.jpeg',
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false,
    translator_type: 'none'
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  favorited: false,
  retweeted: false,
  lang: 'en'
}